[package]
name = "crystality_revm"
version = "0.1.0"
license.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true
repository.workspace = true
documentation.workspace = true
homepage.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
revm = "29.0.0"
crossbeam-channel = "0.5"
core_affinity = "0.8"
crossbeam = "0.8"

[lints]
workspace = true
